CREATE TABLE `getx_attachment` (
	`ID` VARCHAR(30) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`GETX_ID` VARCHAR(30) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`GETX_TYPE` VARCHAR(30) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`TURNOVER_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`PROFITABILITY_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`SKILLED_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`UNSKILLED_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`EXPORT_REVENUE_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`DIVERSIFY_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`TECHNOLOGY_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`NG_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`FILE_ATTACHMENT` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`COMPANY_ID` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`MODULE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ASSESSMENT_YEAR` INT(10) UNSIGNED NULL DEFAULT NULL,
	`UPDATED_AT` DATETIME NULL DEFAULT NULL,
	`UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` DATETIME NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_getx_attachment_company_profile` (`COMPANY_ID`) USING BTREE,
	INDEX `FK_getx_attachment_getx_kpi` (`GETX_ID`) USING BTREE,
	CONSTRAINT `FK_getx_attachment_company_profile` FOREIGN KEY (`COMPANY_ID`) REFERENCES `company_profile` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_getx_attachment_getx_kpi` FOREIGN KEY (`GETX_ID`) REFERENCES `getx_kpi` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;
