CREATE TABLE `getx_sign` (
	`ID` VARCHAR(30) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`GETX_ID` VARCHAR(30) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`GETX_TYPE` VARCHAR(30) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BUS_OWNER_NAME` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BUS_OWNER_DATE` DATE NULL DEFAULT NULL,
	`BUS_OWNER` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BUS_COACH_NAME` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BUS_COACH_DATE` DATE NULL DEFAULT NULL,
	`BUS_COACH` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CHECKER_NAME` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CHECKER_DATE` DATE NULL DEFAULT NULL,
	`CHECKER` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`COMPANY_ID` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`MODULE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ASSESSMENT_YEAR` INT(10) UNSIGNED NULL DEFAULT NULL,
	`UPDATED_AT` DATETIME NULL DEFAULT NULL,
	`UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` DATETIME NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_getx_sign_company_profile` (`COMPANY_ID`) USING BTREE,
	CONSTRAINT `FK_getx_sign_company_profile` FOREIGN KEY (`COMPANY_ID`) REFERENCES `slv`.`company_profile` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
