CREATE TABLE `user_public` (
	`NAME` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`SOURCE` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`EMAIL` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`AVATAR` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`STATUS` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ROLE` INT(10) NOT NULL DEFAULT '0',
	`PHONE` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`GENDER` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`DOB` DATE NULL DEFAULT NULL,
	`PWD` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`OPT_FOR_MARKETING` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`COMPANY_ID` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`UPDATED_AT` DATETIME NULL DEFAULT NULL,
	`UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` DATETIME NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`EMAIL`) USING BTREE,
	INDEX `FK_user_public_user_role` (`ROLE`) USING BTREE,
	CONSTRAINT `FK_user_public_user_role` FOREIGN KEY (`ROLE`) REFERENCES `slv`.`user_role` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;
