CREATE TABLE `user` (
	`USER` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ROLE` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`UPDATED_AT` DATETIME NULL DEFAULT NULL,
	`UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` DATETIME NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci'
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
